version: '2.1'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Uptime Kuma
      - flame.url=${UPTIMEKUMA_URL}
      - flame.icon=cloud-check
